Add files via upload

diff --git a/openresty b/openresty
--- a/openresty
+++ b/openresty
@@ -1,211 +1,139 @@
 #!/bin/sh
-
+#
+# openresty     Startup script for openresty/nginx
+#
+# chkconfig: - 85 15
+# processname: nginx
+# config: /usr/local/openresty/nginx/conf/nginx.conf
+# config: /etc/sysconfig/openresty
+# pidfile: /var/run/openresty.pid
+# description: nginx(openresty) is a HTTP and reverse proxy server
+#
 ### BEGIN INIT INFO
-# Provides:	  openresty
-# Required-Start:    $local_fs $remote_fs $network $syslog $named
-# Required-Stop:     $local_fs $remote_fs $network $syslog $named
-# Default-Start:     2 3 4 5
-# Default-Stop:      0 1 6
-# Short-Description: starts the Openresty(nginx) web server
-# Description:       starts Openresty(nginx) using start-stop-daemon
+# Provides: nginx
+# Required-Start: $local_fs $remote_fs $network
+# Required-Stop: $local_fs $remote_fs $network
+# Default-Start: 2 3 4 5
+# Default-Stop: 0 1 6
+# Short-Description: start and stop nginx/openresty
 ### END INIT INFO
-
-PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
-DESC="Openresty (Nginx) Daemon"
-NAME=nginx
-PREFIX=/usr/local/openresty/nginx
-CONF=$PREFIX/conf/$NAME.conf
-DAEMON=$PREFIX/sbin/$NAME
-
-# Include nginx defaults if available
-if [ -r /etc/default/nginx ]; then
-	. /etc/default/nginx
+  
+# Source function library.
+. /etc/rc.d/init.d/functions
+  
+if [ -f /etc/sysconfig/openresty ]; then
+    . /etc/sysconfig/openresty
 fi
-
-test -x $DAEMON || exit 0
-
-. /lib/init/vars.sh
-. /lib/lsb/init-functions
-
-# Try to extract nginx pidfile
-PID=$(cat ${CONF} | grep -Ev '^\s*#' | awk 'BEGIN { RS="[;{}]" } { if ($1 == "pid") print $2 }' | head -n1)
-if [ -z "$PID" ]
-then
-	PID=$PREFIX/logs/$NAME.pid
-fi
-
-# Check if the ULIMIT is set in /etc/default/nginx
-if [ -n "$ULIMIT" ]; then
-	# Set the ulimits
-	ulimit $ULIMIT
-fi
-
-#
-# Function that starts the daemon/service
-#
-do_start()
-{
-	# Return
-	#   0 if daemon has been started
-	#   1 if daemon was already running
-	#   2 if daemon could not be started
-	start-stop-daemon --start --quiet --pidfile $PID --exec $DAEMON --test > /dev/null \
-		|| return 1
-	start-stop-daemon --start --quiet --pidfile $PID --exec $DAEMON -- \
-		$DAEMON_OPTS 2>/dev/null \
-		|| return 2
+  
+prog=nginx
+nginx=${NGINX-/usr/local/openresty/nginx/sbin/nginx}
+conffile=${CONFFILE-/usr/local/openresty/nginx/conf/nginx.conf}
+lockfile=${LOCKFILE-/var/lock/subsys/openresty}
+pidfile=${PIDFILE-/var/run/openresty.pid}
+SLEEPMSEC=100000
+RETVAL=0
+  
+start() {
+    echo -n $"Starting $prog: "
+  
+    daemon --pidfile=${pidfile} ${nginx} -c ${conffile}
+    RETVAL=$?
+    echo
+    [ $RETVAL = 0 ] && touch ${lockfile}
+    return $RETVAL
 }
-
-test_nginx_config() {
-	$DAEMON -t $DAEMON_OPTS >/dev/null 2>&1
+  
+stop() {
+    echo -n $"Stopping $prog: "
+    killproc -p ${pidfile} ${prog}
+    RETVAL=$?
+    echo
+    [ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}
 }
-
-#
-# Function that stops the daemon/service
-#
-do_stop()
-{
-	# Return
-	#   0 if daemon has been stopped
-	#   1 if daemon was already stopped
-	#   2 if daemon could not be stopped
-	#   other if a failure occurred
-	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PID --name $NAME
-	RETVAL="$?"
-
-	sleep 1
-	return "$RETVAL"
+  
+reload() {
+    echo -n $"Reloading $prog: "
+    killproc -p ${pidfile} ${prog} -HUP
+    RETVAL=$?
+    echo
 }
-
-#
-# Function that sends a SIGHUP to the daemon/service
-#
-do_reload() {
-	start-stop-daemon --stop --signal HUP --quiet --pidfile $PID --name $NAME
-	return 0
+  
+upgrade() {
+    oldbinpidfile=${pidfile}.oldbin
+  
+    configtest -q || return 6
+    echo -n $"Staring new master $prog: "
+    killproc -p ${pidfile} ${prog} -USR2
+    RETVAL=$?
+    echo
+    /bin/usleep $SLEEPMSEC
+    if [ -f ${oldbinpidfile} -a -f ${pidfile} ]; then
+        echo -n $"Graceful shutdown of old $prog: "
+        killproc -p ${oldbinpidfile} ${prog} -QUIT
+        RETVAL=$?
+        echo
+    else
+        echo $"Upgrade failed!"
+        return 1
+    fi
 }
-
-#
-# Rotate log files
-#
-do_rotate() {
-	start-stop-daemon --stop --signal USR1 --quiet --pidfile $PID --name $NAME
-	return 0
+  
+configtest() {
+    if [ "$#" -ne 0 ] ; then
+        case "$1" in
+            -q)
+                FLAG=$1
+                ;;
+            *)
+                ;;
+        esac
+        shift
+    fi
+    ${nginx} -t -c ${conffile} $FLAG
+    RETVAL=$?
+    return $RETVAL
 }
-
-#
-# Online upgrade nginx executable
-#
-# "Upgrading Executable on the Fly"
-# http://nginx.org/en/docs/control.html
-#
-do_upgrade() {
-	# Return
-	#   0 if nginx has been successfully upgraded
-	#   1 if nginx is not running
-	#   2 if the pid files were not created on time
-	#   3 if the old master could not be killed
-	if start-stop-daemon --stop --signal USR2 --quiet --pidfile $PID --name $NAME; then
-		# Wait for both old and new master to write their pid file
-		while [ ! -s "${PID}.oldbin" ] || [ ! -s "${PID}" ]; do
-			cnt=`expr $cnt + 1`
-			if [ $cnt -gt 10 ]; then
-				return 2
-			fi
-			sleep 1
-		done
-		# Everything is ready, gracefully stop the old master
-		if start-stop-daemon --stop --signal QUIT --quiet --pidfile "${PID}.oldbin" --name $NAME; then
-			return 0
-		else
-			return 3
-		fi
-	else
-		return 1
-	fi
+  
+rh_status() {
+    status -p ${pidfile} ${nginx}
 }
-
+  
+# See how we were called.
 case "$1" in
-	start)
-		[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
-		do_start
-		case "$?" in
-			0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-			2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-		esac
-		;;
-	stop)
-		[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
-		do_stop
-		case "$?" in
-			0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-			2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-		esac
-		;;
-	restart)
-		log_daemon_msg "Restarting $DESC" "$NAME"
-
-		# Check configuration before stopping nginx
-		if ! test_nginx_config; then
-			log_end_msg 1 # Configuration error
-			exit 0
-		fi
-
-		do_stop
-		case "$?" in
-			0|1)
-				do_start
-				case "$?" in
-					0) log_end_msg 0 ;;
-					1) log_end_msg 1 ;; # Old process is still running
-					*) log_end_msg 1 ;; # Failed to start
-				esac
-				;;
-			*)
-				# Failed to stop
-				log_end_msg 1
-				;;
-		esac
-		;;
-	reload|force-reload)
-		log_daemon_msg "Reloading $DESC configuration" "$NAME"
-
-		# Check configuration before reload nginx
-		#
-		# This is not entirely correct since the on-disk nginx binary
-		# may differ from the in-memory one, but that's not common.
-		# We prefer to check the configuration and return an error
-		# to the administrator.
-		if ! test_nginx_config; then
-			log_end_msg 1 # Configuration error
-			exit 0
-		fi
-
-		do_reload
-		log_end_msg $?
-		;;
-	configtest|testconfig)
-		log_daemon_msg "Testing $DESC configuration"
-		test_nginx_config
-		log_end_msg $?
-		;;
-	status)
-		status_of_proc -p $PID "$DAEMON" "$NAME" && exit 0 || exit $?
-		;;
-	upgrade)
-		log_daemon_msg "Upgrading binary" "$NAME"
-		do_upgrade
-		log_end_msg 0
-		;;
-	rotate)
-		log_daemon_msg "Re-opening $DESC log files" "$NAME"
-		do_rotate
-		log_end_msg $?
-		;;
-	*)
-		echo "Usage: $NAME {start|stop|restart|reload|force-reload|status|configtest|rotate|upgrade}" >&2
-		exit 3
-		;;
+    start)
+        rh_status >/dev/null 2>&1 && exit 0
+        start
+        ;;
+    stop)
+        stop
+        ;;
+    status)
+        rh_status
+        RETVAL=$?
+        ;;
+    restart)
+        configtest -q || exit $RETVAL
+        stop
+        start
+        ;;
+    upgrade)
+        upgrade
+        ;;
+    condrestart|try-restart)
+        if rh_status >/dev/null 2>&1; then
+            stop
+            start
+        fi
+        ;;
+    force-reload|reload)
+        reload
+        ;;
+    configtest)
+        configtest
+        ;;
+    *)
+        echo $"Usage: $prog {start|stop|restart|condrestart|try-restart|force-reload|upgrade|reload|status|help|configtest}"
+        RETVAL=2
 esac
-
-:
+  
+exit $RETVAL
